name: React build
on: 
  - push
  - workflow_dispatch
jobs: 
  build_app: 
    runs-on: ubuntu-latest
    steps: 
      - name: Read repository code
        uses: actions/checkout@v3
      - name: Installing dependencies
        # Prefereble ci method instead of install if your project has lock file
        run: npm ci
      - name: Testing application
        run: npm run test
      - name: Building application
        run: npm run build