name: 'React deployment'
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      # - name: 'Install dependencies'
        # run: npm install --config
      - name: 'Build project'
        run: npm run build
      - name: 'Test project'
        run: npm run test    